#!/usr/bin/env bash
# shellcheck disable=SC1091
set -eo pipefail

source "${RECORDS_SH:?}/records.sh"
# shellcheck disable=SC2034
LOGPROGRAM=install-nixos
INSTALLTMP=/tmp/install-nixos
UNATTENDEDPATH=/iso/unattended.json

main() {
  DOC="install-nixos - Install NixOS on the current machine
Usage:
  install-nixos [options]

Options:
  --abort-msg    Show an abort message for 5 secs before launching
  --auto-reboot  Automatically reboot the machine after a successful install
  --no-update    Don't \`nix run\` \$UPDATEURL
  --no-sb-check  Don't check if the system is in Setup Mode
  --no-mount     Don't mount the host system flake source if available
  --unattended   Enable unattended mode, if /iso/unattended.json exists
  --repourl=URL    Set the installation repository URL [default: \$REPOURL]
  --install-dev <DEVPATH>  Devicepath to install to
  --nixosconfig <CONFIG>   Name of nixosConfiguration to install
"
# docopt parser below, refresh this parser with `docopt.sh installer`
# shellcheck disable=2016,2086,2329,1090,1091,2034
docopt() { local v='2.0.3'; source "${DOCOPT_LIB_SH:?}/docopt-lib.sh" "$v" || {
ret=$?;printf -- "exit %d\n" "$ret";exit "$ret";};set -e
trimmed_doc=${DOC:0:678};usage=${DOC:53:32};digest=dd8d3;options=(' --abort-ms'\
'g 0' ' --auto-reboot 0' ' --no-update 0' ' --no-sb-check 0' ' --no-mount 0' \
' --unattended 0' ' --repourl 1' ' --install-dev 1' ' --nixosconfig 1')
node_0(){ switch __abort_msg 0;};node_1(){ switch __auto_reboot 1;};node_2(){
switch __no_update 2;};node_3(){ switch __no_sb_check 3;};node_4(){ switch \
__no_mount 4;};node_5(){ switch __unattended 5;};node_6(){ value __repourl 6;}
node_7(){ value __install_dev 7;};node_8(){ value __nixosconfig 8;};node_9(){
optional 0 1 2 3 4 5 6 7 8;};cat <<<' docopt_exit() { [[ -n $1 ]] && printf \
"%s\n" "$1" >&2;printf "%s\n" "${DOC:53:32}" >&2;exit 1;}';local \
varnames=(__abort_msg __auto_reboot __no_update __no_sb_check __no_mount \
__unattended __repourl __install_dev __nixosconfig) varname;for varname in \
"${varnames[@]}"; do unset "var_$varname";done;parse 9 "$@";local \
p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do unset "$p$varname"
done;eval $p'__abort_msg=${var___abort_msg:-false};'$p'__auto_reboot=${var___a'\
'uto_reboot:-false};'$p'__no_update=${var___no_update:-false};'$p'__no_sb_chec'\
'k=${var___no_sb_check:-false};'$p'__no_mount=${var___no_mount:-false};'$p'__u'\
'nattended=${var___unattended:-false};'$p'__repourl=${var___repourl:-'\
"'"'$REPOURL'"'"'};'$p'__install_dev=${var___install_dev:-};'$p'__nixosconfig='\
'${var___nixosconfig:-};';local docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && \
docopt_i=2;for ((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; \
do declare -p "$p$varname";done;done;}
# docopt parser above, complete command for generating this parser is `docopt.sh --library='"${DOCOPT_LIB_SH:?}/docopt-lib.sh"' installer`
  eval "$(docopt "$@")"

  mkdir -p $INSTALLTMP

  # shellcheck disable=SC2064
  trap "error \"Installation aborted. You can restart the installer with 'sudo install-nixos'.\"" EXIT

  [[ $(id -u) = 0 ]] || fatal "Must run as root"

  # shellcheck disable=SC2154
  ! $__abort_msg || timeout_msg 5 "Launching the installer in %ds. Press <ENTER> to abort..."

  (umount $INSTALLTMP/flake-src 2>&1 || true) | pipe_debug
  mkdir -p $INSTALLTMP/flake-src
  # shellcheck disable=SC2154
  if ! $__no_mount && mount -t 9p -o trans=virtio -o version=9p2000.L pwd $INSTALLTMP/flake-src 2>&1 | pipe_debug; then
    info "Mounted host system flake source, disable this with '--no-mount'"
    [[ $UPDATEURL != "$REPOURL#"* ]] || UPDATEURL="$INSTALLTMP/flake-src#${UPDATEURL#"$REPOURL#"}"
    REPOURL=$INSTALLTMP/flake-src
  elif [[ $__repourl != \$REPOURL ]]; then
    REPOURL=$__repourl
  elif [[ -z $REPOURL ]]; then
    docopt_exit "No --repourl specified"
  fi

  if ! curl -skf --connect-timeout 1 https://cache.nixos.org >/dev/null; then
    info "Waiting for an internet connection..."
    local timeout=10
    while true; do
      sleep 1
      if curl -skf --connect-timeout 1 https://cache.nixos.org >/dev/null; then
        break
      elif (( --timeout == 0 )); then
        warning "Timed out waiting for cache.nixos.org to respond."
      fi
    done
  fi

  # shellcheck disable=SC2154
  if ! $__no_update; then
    if [[ -n $UPDATEURL ]]; then
      info "Self updating... building and running new installer"
      local rerun_args=(--no-update)
      for e; do [[ $e = --abort-msg ]] || rerun_args+=("$e"); done
      trap "" EXIT
      info "If this fails, you can restart the installer without updating by running 'sudo install-nixos'"
      exec nix run --tarball-ttl 0 "$UPDATEURL" -- "${rerun_args[@]}"
    else
      info "Skipping self-update, \$UPDATEURL is not set"
    fi
  fi

  # Instead of using traps, we clean up before running an install
  # This way you can debug the state of the install if it crashes
  info "Cleaning leftovers from previous install attempt"
  ! findmnt /mnt/boot >/dev/null || umount /mnt/boot
  if findmnt /mnt >/dev/null; then
    umount /mnt
  fi
  [[ ! -b /dev/mapper/nixos ]] || cryptsetup close nixos

  # Make sure we can enroll the secure boot keys
  # shellcheck disable=SC2154
  $__no_sb_check || sbctl status --json | jq -e .setup_mode >/dev/null 2>&1 || \
    fatal "Your system is not in Setup Mode! Reset secure boot keys so they can be enrolled. You can disable this check with '--no-sb-check'"

  local unattended=false installdev nixosconfig hashedpasswordfile hashedpassword enrollfallbackpassword
  # shellcheck disable=SC2154
  [[ ! -e $UNATTENDEDPATH ]] || unattended=$__unattended
  ! $unattended || info "Commencing unattended installation"
  if [[ -n $__install_dev ]]; then
    installdev=$__install_dev
  elif $unattended; then
    installdev=$(jq -re .installDev "$UNATTENDEDPATH") || \
      fatal "Key \"installDev\" missing in %s, unable to continue with unattended install." "$UNATTENDEDPATH"
  else
    installdev=$(get_installdev)
  fi
  if [[ -n $__nixosconfig ]]; then
    nixosconfig=$__nixosconfig
  elif $unattended; then
    nixosconfig=$(jq -re .nixOSConfig "$UNATTENDEDPATH") || \
      fatal "Key \"nixOSConfig\" missing in %s, unable to continue with unattended install." "$UNATTENDEDPATH"
  else
    nixosconfig=$(get_nixosconfig)
  fi
  if hashedpasswordfile=$(get_config "$nixosconfig" sbfde.hashedPasswordFile | jq -re); then
    if $unattended; then
      hashedpassword=$(jq -r '.hashedPassword // empty' "$UNATTENDEDPATH")
    else
      get_secret $INSTALLTMP/user_password "Enter your user password"
      hashedpassword=$(cat $INSTALLTMP/user_password | mkpasswd --stdin)
    fi
  fi
  enrollfallbackpassword=$(get_config "$nixosconfig" sbfde.enrollFallbackPassword | jq -r)
  if $enrollfallbackpassword; then
    ! $unattended || fatal "LUKS fallback password enabled. This is unsupported in unattended mode. Disable with sbfde.enrollFallbackPassword=false"
    # Prompt, then prepare enrollment of a fallback FDE password
    (umask 0066; touch $INSTALLTMP/fallback.key)
    get_secret $INSTALLTMP/fallback.key "Enter a disk encryption fallback password"
  else
    rm -f $INSTALLTMP/fallback.key
  fi

  local recoverykeypath enrollemptykey repartdefinitions
  recoverykeypath=$(get_config "$nixosconfig" sbfde.recoveryKeyPath | jq -re)
  enrollemptykey=$(get_config "$nixosconfig" sbfde.enrollEmptyKey | jq -r)
  repartdefinitions=$(nix build "$REPOURL#nixosConfigurations.\"$nixosconfig\".config.sbfde.repartDefinitions" --print-out-paths)

  clear

  info "Formatting disk"
  mkdir -p "$(dirname $INSTALLTMP/empty.key)"
  (umask 0066; touch $INSTALLTMP/empty.key)
  systemd-repart --dry-run=no --empty=force \
    --key-file $INSTALLTMP/empty.key \
    --definitions "$repartdefinitions" "$installdev"

  # When systemd-repart returns the device nodes for the partitions might not exist yet.
  # Give udev a second or two.
  sleep 2

  # Properly discover devpaths of the partitions, slapping on a "1" and "2" won't work for e.g. /dev/nvme0n1p2
  local esp_devpath root_devpath
  esp_devpath=$(lsblk -JO "$installdev" | jq -r '.blockdevices[].children[] | select(.partn==1) | .path')
  root_devpath=$(lsblk -JO "$installdev" | jq -r '.blockdevices[].children[] | select(.partn==2) | .path')

  # Attach the encrypted disk using the empty password
  info "Attaching encrypted disk"
  cryptsetup open --key-file=$INSTALLTMP/empty.key "$root_devpath" nixos

  info "Mounting root & boot"
  mount /dev/mapper/nixos /mnt
  (umask 0066; mkdir /mnt/boot)
  mount "$esp_devpath" /mnt/boot

  # Enroll a recovery key so the system can update e.g. the TPM2 key without having to prompt for the fallback password
  info "Enrolling LUKS recovery key"
  local recoverykey
  recoverykey=$(systemd-cryptenroll --unlock-key-file=$INSTALLTMP/empty.key --recovery "$root_devpath")
  # We can't just redirect the output from above
  # The recovery key is output with a trailing newline that is not part of the key
  mkdir -p "/mnt$(dirname "$recoverykeypath")"
  (umask 0066; printf "%s" "$recoverykey" >"/mnt$recoverykeypath")

  if $enrollfallbackpassword; then
    info "Enrolling LUKS fallback password"
    cryptsetup luksAddKey --key-file=$INSTALLTMP/empty.key --new-keyfile $INSTALLTMP/fallback.key "$root_devpath"
  fi

  if ! $enrollemptykey; then
    info "Unenrolling LUKS empty key"
    systemd-cryptenroll --unlock-key-file="/mnt$recoverykeypath" --wipe-slot=empty
  fi

  info "Installing NixOS"
  nixos-install --verbose --no-root-password --root /mnt --flake "$REPOURL#$nixosconfig"

  if [[ -n $hashedpasswordfile ]]; then
    info "Copying hashed user password to the system"
    mkdir -p "$(dirname "/mnt$hashedpasswordfile")"
    chmod 755 "$(dirname "/mnt$hashedpasswordfile")"
    printf "%s" "$hashedpassword" >"/mnt$hashedpasswordfile"
    chmod 600 "/mnt$hashedpasswordfile"
  fi

  # Workaround for lanzaboote not installing the bootloader into the ESP
  info "Installing bootloader"
  mv /mnt/boot/EFI/BOOT/BOOTX64.EFI /mnt/boot/EFI/BOOT/BOOTX64.EFI.BAK
  mv /mnt/boot/EFI/systemd/systemd-bootx64.efi /mnt/boot/EFI/systemd/systemd-bootx64.efi.bak
  bootctl --esp-path /mnt/boot install
  mv /mnt/boot/EFI/BOOT/BOOTX64.EFI.BAK /mnt/boot/EFI/BOOT/BOOTX64.EFI
  mv /mnt/boot/EFI/systemd/systemd-bootx64.efi.bak /mnt/boot/EFI/systemd/systemd-bootx64.efi

  info "Unmounting root & boot"
  umount /mnt/boot
  umount /mnt

  info "Detaching encrypted disk"
  cryptsetup close nixos

  trap "" EXIT
  # shellcheck disable=SC2154
  if $__auto_reboot; then
    timeout_msg 5 "Rebooting in %ds. Press <ENTER> to abort..." || fatal "Reboot aborted"
    reboot
  else
    info "Installation completed! Run \`reboot' to boot into your new system."
  fi
}

get_installdev() {
  local dev installdev text dialog_args=() devices=()
  while read -r -d $'\n' dev text; do
    devices+=("$dev")
    dialog_args+=("$dev" "$text")
  done < <(lsblk -JaO | jq -r '.blockdevices[] | select(
      .group == "disk" and
      .type != "loop" and
      .fstype != "iso9660"
    ) | "\(.path) \([(.children // [])[] | .label | select(. != "ESP" and . != null)] | first // "unlabeled"), \(.serial // "No serial") (\(.model // "Unknown model"), \(.size))"')
  [[ ${#devices[@]} -gt 0 ]] || fatal "No disk installation candidates found. Run \`install-nixos --install-dev <DEVPATH>\`"
  while true; do
    installdev=$(dialog --stdout --menu "Select the disk where NixOS should be installed" 15 80 10 "${dialog_args[@]}")
    [[ -n $installdev ]] || return 1
    if [[ -n $(lsblk -noFSTYPE,PTTYPE "$installdev") ]]; then
      dialog --stdout --yesno "The disk '$installdev' is not empty."$'\nAre you sure you want to wipe all data on it?' 15 80 || \
        continue
    fi
    break
  done
  printf "%s\n" "$installdev"
}

get_nixosconfig() {
  local nixosconfigs nixosconfig dialog_args=()
  nixosconfigs=$(nix flake show --json "$REPOURL" | jq -r '.nixosConfigurations | keys[]')
  while IFS= read -r -d $'\n' nixosconfig; do
    ! get_config "$nixosconfig" sbfde.includeInSelection 2>/dev/null | jq -re >/dev/null || \
      dialog_args+=("$nixosconfig" "$nixosconfig")
  done <<<"$nixosconfigs"
  [[ ${#dialog_args[@]} -gt 0 ]] || fatal "No usable nixosConfigurations found."
  dialog --stdout --menu "Select the NixOS configuration you would like to install" 15 80 10 "${dialog_args[@]}"
}

get_secret() {
  local save_path=$1 message=$2 password prev_pass
  [[ ! -e $save_path ]] || prev_pass=$(cat "$save_path")
  while true; do
    password=$(dialog --stdout --insecure --passwordbox "$message" 7 45 "$prev_pass")
    [[ $password = "$prev_pass" ]] || prev_pass=""
    if [[ -n $prev_pass && $password = "$prev_pass" ]]; then
      break
    elif [[ -z $password ]]; then
      dialog --stdout --msgbox "Password must not be empty" 7 45
    elif [[ $password != "$(dialog --stdout --insecure --passwordbox "Retype to confirm the password" 7 45 "$prev_pass")" ]]; then
      dialog --stdout --msgbox "Passwords do not match!" 7 45
    else
      break
    fi
  done
  printf "%s" "$password" >"$save_path"
}

get_config() {
  local nixosconfig=$1 configpath=$2
  nix eval --json "$REPOURL#nixosConfigurations.\"$nixosconfig\".config.$configpath" || \
    fatal "Unable to retrieve configpath %s for host %s" "$configpath" "$nixosconfig"
}

timeout_msg() {
  local timeout=$1 msg_tpl=$2 rendered_msg ret
  until (( timeout == 0 )); do
    # shellcheck disable=SC2059
    rendered_msg=$(printf "\r$msg_tpl" "$timeout")
    ret=0
    read -r -p "$rendered_msg" -t 1 || ret=$?
    [[ $ret = 142 ]] || return 1
    : $((timeout--))
  done
  printf "\n"
  return 0
}

main "$@"
